### Get personal questions
GET {{backend}}/api/questions
Authorization: Bearer {{auth_token}}

### Get all questions
GET {{backend}}/api/questions/all
Authorization: Bearer {{auth_token}}

### Create question
POST {{backend}}/api/questions
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "null",
  "question": "Есть ли жизнь на марсе?"
}

> {%
    client.global.set("questionId", response.body.items[0].id);
%}

### Delete question
DELETE {{backend}}/api/questions/{{questionId}}
