### Get list of personal targets
GET {{backend}}/api/{{version}}/{{format}}/targets/personal
Authorization: Bearer {{auth_token}}

### Get list of public targets
GET {{backend}}/api/{{version}}/{{format}}/targets/public
Authorization: Bearer {{auth_token}}

### Create new target
POST {{backend}}/api/{{version}}/{{format}}/targets/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{ "json": "{\"title\":\"Разобраться с документацией .http\",\"overview\":\"Я впервые сталкиваюсь с подобным форматом и хотел бы его изучить. \",\"progress\":0,\"tasks\":[]}" }

> {%
    client.global.set("targetId", response.body.items[0].id);
%}

### Get target by id
GET {{backend}}/api/{{version}}/{{format}}/targets/{{targetId}}
Authorization: Bearer {{auth_token}}

### Update target
PUT {{backend}}/api/{{version}}/{{format}}/targets/{{targetId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{ "id": "{{targetId}}", "json": "{\"title\":\"Разобраться с документацией .http\",\"overview\":\"Я впервые сталкиваюсь с подобным форматом и хотел бы его изучить. \",\"progress\":0,\"tasks\":[{\"title\":\"изучить документацию\",\"overview\":\"\",\"progress\":0,\"tasks\":[]}]}" }

### Delete target
DELETE {{backend}}/api/{{version}}/{{format}}/targets/{{targetId}}
Authorization: Bearer {{auth_token}}
