### Create user
POST {{host}}/auth/signup
Content-Type: application/json

{ "login": "login", "email": "login@email.com", "password": "123" }

### Login
POST {{host}}/auth/signin
Content-Type: application/json

{ "login": "login", "password": "123" }

### Get access token with valid token (200)
GET {{host}}/auth/access_token


### Logout
GET {{host}}/auth/signout
