### Get cookies
GET {{backend}}/api/auth/cookie
Authorization: Bearer {{auth_token}}

### Get manifest
GET {{backend}}/api/user/manifest
Authorization: Bearer {{auth_token}}

### Get isues from github
GET {{backend}}/api/github
Authorization: Bearer {{auth_token}}

### Get assets
GET {{backend}}/assets/guest/info.json
Authorization: Bearer {{auth_token}}

### Get personal activity
GET {{backend}}/api/{{version}}/{{format}}/activity/personal
Authorization: Bearer {{auth_token}}

### Get workbook list
GET {{backend}}/api/{{version}}/{{format}}/workbook/personal
Authorization: Bearer {{auth_token}}

### Get new workbook
GET {{backend}}/api/{{version}}/{{format}}/workbook/new
Authorization: Bearer {{auth_token}}

### Create new workbook
#@name newWorkbook
POST {{backend}}/api/{{version}}/{{format}}/workbook/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{ "json" : "{\"question\":\"\",\"blocks\":[{\"text\":\"### Test new workbook\",\"type\":\"markdown\"}]}" }

> {%
    client.global.set("id", response.body.items[0].id);
%}

### Get workbook by id
#@name oneWorkbook
GET {{backend}}/api/{{version}}/{{format}}/workbook/{{id}}
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("id", response.body.items[0].id);
%}

### Update workbook
PUT {{backend}}/api/{{version}}/{{format}}/workbook/{{id}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{ "id": "{{id}}", "json" : "{\"question\":\"\",\"blocks\":[{\"text\":\"### Test new workbook _updated_\",\"type\":\"markdown\"}]}" }

### Delete workbook
DELETE {{backend}}/api/{{version}}/{{format}}/workbook/{{id}}
Authorization: Bearer {{auth_token}}
