### Get cookies
GET {{backend}}/api/auth/cookie
Authorization: Bearer {{auth_token}}

### Get manifest
GET {{backend}}/api/user/manifest
Authorization: Bearer {{auth_token}}

### Get isues from github
GET {{backend}}/api/github
Authorization: Bearer {{auth_token}}

### Get assets
GET {{backend}}/assets/guest/info.json
Authorization: Bearer {{auth_token}}

### Get personal activity
GET {{backend}}/api/{{version}}/{{format}}/activity/personal
Authorization: Bearer {{auth_token}}
