### Get a list of personal templates
GET {{backend}}/api/{{version}}/{{format}}/templates/personal
Authorization: Bearer {{auth_token}}

### Get a list of public templates
GET {{backend}}/api/{{version}}/{{format}}/templates/public
Authorization: Bearer {{auth_token}}

### Create template
POST {{backend}}/api/{{version}}/{{format}}/templates/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "accessTag": "PRIVATE",
  "json": "{\"title\":\"Разобраться с документацией .http\",\"overview\":\"Я впервые сталкиваюсь с подобным форматом и хотел бы его изучить. \",\"progress\":0,\"tasks\":[]}"
}

> {%
    client.global.set("templateId", response.body.items[0].id);
%}

### Delete template
DELETE {{backend}}/api/{{version}}/{{format}}/templates/{{templateId}}
Authorization: Bearer {{auth_token}}
