@naris_api_host = http://localhost:3200
@auth_host = http://localhost:3100
@version = v1
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXVpZCI6IjhiMzAxZTk5LWU0NjctNDUwYS1iYzhlLTBmMmQ3MmU0ZDBiMCIsImVtYWlsIjoiYmFyQGZvby5jb20iLCJ1c2VyUm9sZSI6Imd1ZXN0IiwiaWF0IjoxNjg3NTE5NzQ2LCJleHAiOjE2ODc1MjA2NDZ9.-R6K1byfzrqbEIUOemC_pIYgTj44awVtMNj9MD2kzEc
@user_uuid = 8b301e99-e467-450a-bc8e-0f2d72e4d0b0

# #####################################
# You need db and auth services running
# #####################################


# #####################################
# Preparation works begin
# #####################################

### Register a user in the db
POST {{auth_host}}/auth/signup
Content-Type: application/json

{ "login": "login", "email": "bar@foo.com", "password": "password" }

### Sign in
POST {{auth_host}}/auth/signin
Content-Type: application/json

{ "login": "login", "password": "password" }
# { "login": "login1", "password": "password" }

### Sign out
GET {{auth_host}}/auth/signout

### Get an access token
# save a received token in @access_token
# every time when an unauthorized error is received in a response from naris-api
GET {{auth_host}}/auth/access_token

# #####################################
# Preparation works end
# #####################################

### Get questions
GET {{naris_api_host}}/api/{{version}}/questions
Authorization: Bearer {{access_token}}

### Get the questions for a current user
GET {{naris_api_host}}/api/{{version}}/questions?userUuid={{user_uuid}}
Authorization: Bearer {{access_token}}

### Create a question
POST {{naris_api_host}}/api/{{version}}/questions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{ "question": "sd" }

### Delete a question
@question_id = 17
DELETE {{naris_api_host}}/api/{{version}}/questions/{{question_id}}
Authorization: Bearer {{access_token}}
