name: Test

on:
  push:
    branches:
      - ci-latest
  pull_request:
    # paths-ignore:
    #   - 'src/bff-service/**'
    branches:
      - ci-latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
